apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sawtooth
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: sawtooth
    spec:
      containers:
        - name: sawtooth-settings-tp
          image: hyperledger/sawtooth-settings-tp:1.1
          command:
            - bash
          args:
            - -c
            - "settings-tp -vv -C tcp://sawtooth-validator:4004"

        - name: sawtooth-xo-tp-go
          image: hyperledger/sawtooth-xo-tp-go:1.1
          command:
            - bash
          args:
            - -c
            - "xo-tp-go -vv -C tcp://sawtooth-validator:4004"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sawtooth-validator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: sawtooth-validator
    spec:
      containers:
        - name: sawtooth-validator
          image: hyperledger/sawtooth-validator:1.1
          ports:
            - name: tp
              containerPort: 4004
            - name: consensus
              containerPort: 5050
            - name: validators
              containerPort: 8800
          command:
            - bash
          args:
            - -c
            - "sawadm keygen \
            && sawtooth keygen my_key \
            && sawset genesis -k /root/.sawtooth/keys/my_key.priv \
            && sawadm genesis config-genesis.batch \
            && sawtooth-validator -vv \
                --endpoint tcp://0.0.0.0:8800 \
                --bind component:tcp://0.0.0.0:4004 \
                --bind consensus:tcp://0.0.0.0:5050 \
                --bind network:tcp://0.0.0.0:8800"

        - name: sawtooth-devmode-engine
          image: hyperledger/sawtooth-devmode-engine-rust:1.1
          command:
            - bash
          args:
            - -c
            - "devmode-engine-rust -C tcp://localhost:5050"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sawtooth-rest-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: sawtooth-rest-api
    spec:
      containers:
        - name: sawtooth-rest-api
          image: hyperledger/sawtooth-rest-api:1.1
          ports:
            - name: api
              containerPort: 8008
          command:
            - bash
          args:
            - -c
            - "sawtooth-rest-api -B 0.0.0.0:8008 -v -C tcp://sawtooth-validator:4004"
---
apiVersion: v1
kind: Pod
metadata:
  name: sawtooth-shell
  namespace: default
  labels:
    name: sawtooth-shell
spec:
  containers:
  - name: sawtooth-shell
    image: hyperledger/sawtooth-shell:1.1
    command:
      - bash
    args:
      - -c
      - "sawtooth keygen && tail -f /dev/null"
---
apiVersion: v1
kind: Service
metadata:
  name: sawtooth-rest-api
spec:
  type: ClusterIP
  selector:
    name: sawtooth-rest-api
  ports:
    - name: "sawtooth-rest-api"
      protocol: TCP
      port: 8008
      targetPort: 8008
---
apiVersion: v1
kind: Service
metadata:
  name: sawtooth-validator
spec:
  type: ClusterIP
  selector:
    name: sawtooth-validator
  ports:
    - name: "consensus"
      protocol: TCP
      port: 5050
      targetPort: 5050
    - name: "tp"
      protocol: TCP
      port: 4004
      targetPort: 4004
    - name: "validator"
      protocol: TCP
      port: 8800
      targetPort: 8800